name: Code check

on:
  push:
    branches: [ "master", "env/prod" ]
  pull_request:
    types: [ "opened", "synchronize" ]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install -D
      - name: Run ESLint
        run: npm run lint

  typecheck:
    name: Typescript Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install -D
      - name: Run typecheck
        run: npm run ts:check